[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Permitir el encabezado CORS para todos los orígenes
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
